### ISSUE TITLE
How would we select scope of which projects and tables to document?

### ISSUE THREAD

**Issue by bastienboutonnet** [bitpicky/dbt-sugar#13]
One thing we'll need to worry about fairly soon is how we manage scopes of dbt projects to document.

Some users might have one repo per dbt projects and some might have several dbt projects in one repo (monorepo-like setup).

We'll probably want to offer in a yaml file or so an ability for users to list the dbt projects (and possibly tables) to include or exclude from the documentation task. It would probably look something like this:
```yaml
dbt_projects:
    - dbt_dwh:
        - exclude: ['table_1', 'table_2']
    - dbt_prediction
```

It'll probably change and I don't even know if that yaml is even valid but at least this captures the gist of it.

**Comment by bastienboutonnet** [comment]
@virvirlopez I think this is going to be relevant to your question around where to store paths and stuff.

I was thinking of having a central config file that would look something like that:
```yaml
projects:
  sugar_test:
    dbt_projects:
      - dbt_dwh:
          project_path: path
          exclude: ["table_1", "table_2"]
      - dbt_prediction:
          project_path: path
  sugar_prod:
    dbt_projects:
      - dbt_marts:
          project_path: path
```

This gives out the following python dict when parsed:
```json
{
  "projects": {
    "sugar_prod": {
      "dbt_projects": [
        {
          "dbt_marts": {
            "project_path": "path"
          }
        }
      ]
    }, 
    "sugar_test": {
      "dbt_projects": [
        {
          "dbt_dwh": {
            "exclude": [
              "table_1", 
              "table_2"
            ], 
            "project_path": "path"
          }
        }, 
        {
          "dbt_prediction": {
            "project_path": "path"
          }
        }
      ]
    }
  }
```

The user would then have to call `dbt-sugar` with maybe a `--sugar-project` argument let's say in our example it would be the `sugar_test` config. This would make available all the scope that we need. This means telling dbt sugar where the dbt profiles are, what tables might be excluded or all sorts of other things down the line

We could then of course have a "default" config which would sit on top of the `project` dict which could point to one of the projects config so that users are not reuired to point to that config for every run.

I'm sure this is not perfect so I'd like to hear your thoughts.
