### ISSUE TITLE
[bug] model name and description is created last in the schema.yml

### ISSUE THREAD

**Issue by bastienboutonnet** [bitpicky/dbt-sugar#165]
#8da76e4 should have corrected this but it doesn't seem like it has in reality. We will need to look into it again right now the output looks like this:
```yaml
- columns:
  - description: This AUD price of the order.
    name: amount
    tests:
    - not_null
  - description: No description for this column.
    name: bank_transfer_amount
  - description: No description for this column.
    name: coupon_amount
  - description: No description for this column.
    name: credit_card_amount
  - description: Identifier of a customer. PK of the dim_company model
    name: customer_id
  - description: No description for this column.
    name: gift_card_amount
  - description: No description for this column.
    name: order_date
  - description: Unique order identifier increasing integer
    name: order_id
  - description: Orders can be in different statuses such as pending, refunded, confirmed etc. This column
      contains this piece of information.
    name: status
  description: The desc
  name: fct_orders
```

but `name` should be the first key and then description and then the columns.
