### ISSUE TITLE
[bug] double check the paths and recursive finding of the config and profiles

### ISSUE THREAD

**Issue by bastienboutonnet** [bitpicky/dbt-sugar#177]
From ajolson on discord:

> I was able to figure it out actually! I put the sugar_config file in the ~/.dbt directory so it searched for profiles.yml in the directory I was running the audit command on
> 
> Couple of things I noted: 
> - If I don't run dbt-sugar commands in the same directory as the sugar_config file it will error out - it says it searches 4 levels higher but doesn't seem to as I tested that
> - If I put a ~ in the path it doesn't go to my home directory....I had to use ../../ etc
> 
> Overall however by putting sugar_config in the same folder as profiles.yml and then making the path use ../../ to go up directories I was able to resolve the issues. 

Need to reproduce and see what's up.

Their config
```yaml
defaults:
  syrup: dbt_he
  target: dev
syrups:
  - name: he
    dbt_projects:
      - name: default
        path: "~/he/snowflake-dbt"
        excluded_tables:
```
