### ISSUE TITLE
dbt_sugar.core.exceptions.DbtProfileFileMissing: DBT_PROFILES_DIR env var is ignored

### ISSUE THREAD

**Issue by smomni** [bitpicky/dbt-sugar#255]
Having the dbt profiles directory configured in `DBT_PROFILES_DIR` environment variable and running `dbt-sugar audit` with the following sugar config results in `dbt_sugar.core.exceptions.DbtProfileFileMissing` error:

```yml
# sugar_config.yml
defaults:
  syrup: jaffle_shop
  target: dev
syrups:
  - name: jaffle_shop
    dbt_projects:
      - name: jaffle_shop
        path: .
```
It looks like `dbt-sugar` is looking for the profiles file only from `~/.dbt` directory.

dbt_sugar version: 0.0.0
