### ISSUE TITLE
Support environment variables in the profiles.yml like in dbt

### ISSUE THREAD

**Issue by vepetkov** [bitpicky/dbt-sugar#282]
When dbt profile is using [environment variables](https://docs.getdbt.com/reference/dbt-jinja-functions/env_var) to set the _profiles.yml_ to configure the connections, dbt-sugar is not expanding these correctly and is using the string as is.

For example, the following profile generates an error when running dbt-sugar doc:

```
dev:
  type: snowflake
  account: "{{ env_var('SNOWSQL_ACCOUNT') }}"
  user: "{{ env_var('SNOWSQL_USER') }}"
  password: "{{ env_var('SNOWSQL_PWD') }}"
```

Error message: 
> (snowflake.connector.errors.ForbiddenError) 250001 (08001): Failed to connect to DB. Verify the account name is correct: {{ env_var('SNOWSQL_ACCOUNT') }}.snowflakecomputing.com:443. HTTP 403: Forbidden

Looking into the dbt codebase, it looks like integrating with the [render_profile](https://github.com/fishtown-analytics/dbt/blob/develop/core/dbt/config/profile.py#L253) function could provide the required functionality.
