### ISSUE TITLE
When several dbt projects are in scope which target should we decide to use?

### ISSUE THREAD

**Issue by bastienboutonnet** [bitpicky/dbt-sugar#38]
The [`sugar_config.yaml`](https://github.com/bitpicky/dbt-sugar/blob/main/tests/sugar_config.yml) allows users to say "I want to document for project X, Y, Z".

Currently the [`DbtProfile`](https://github.com/bitpicky/dbt-sugar/blob/main/dbt_sugar/core/clients/dbt.py#L45) object actually tries to look for a "default" profile. But if this doesn't exist what should we do? 

What if several projects have different targets? How should we decide which db credentials to use?
Should we maybe request another field in the `syrups` which, much like the `paths` to the dbt projects would point to a profile name and target to use? Should we require that people set up a default profile? What if they're using their default profile in their projects already and for some reason it's not compatible or has different use cases?

We could alternatively "solve" this by enforcing our own profile file, but for now we'd like to avoid this since it will require users to maintain a **very similar** profiles.yml file to the one they already have from dbt.

**Comment by bastienboutonnet** [comment]
Adding a bit more context here for @jerco:

In some cases users might maintain several dbt projects (all with a potential matching profile). What we intend to allow users to do when using the documentation task is say "Document models that belong to project x, y,z. This is done by listing dbt projects to "scope" and their paths on disc:

This is done in a `sugar_config.yml` file which looks like this:
```yaml
defaults:
  syrup: syrup_1
  target: dev
syrups:
  - name: syrup_1
    dbt_projects:
      - name: dbt_sugar_test
        path: "./tests/test_dbt_project/dbt_sugar_test"
      - name: another_dbt_project_to_document
        path: "./tests/test_dbt_project/another_dbt_project_to_document"
```

What will happen is that `dbt-sugar` will basically go and open all the yamls, look for definitions and models in the various projects and attempt to write new definitions or even "propagate"/homogenise definitions across models (for more info on this you can check #24 )

So in the case where the two different projects point to a different profile dbt-sugar will probably want to know about that.

One way would potentially be to read the `dbt_project.yml` and then pick whatever the users have in there. Is `profile` a mandatory field in the `dbt_project.yml` file? If so that might be reliable enough.

If not, we may want to extend the `sugar_config.yml` file to have something like:
```yaml
defaults:
  syrup: syrup_1
  target: dev
syrups:
  - name: syrup_1
    dbt_projects:
      - name: dbt_sugar_test
        path: "./tests/test_dbt_project/dbt_sugar_test"
        profile: "dbt_sugar_test_profile" 

```


This second option means there is some duplication which means that is users decide to change the profile of the dbt_project in their project file they would also have to change it in there, which is far from ideal.
